# Generated by Django 5.1.2 on 2024-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='applied_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('considered', 'Considered'), ('declined', 'Declined')], default='submitted', max_length=20),
        ),
    ]
